### ISSUE TITLE
[Bug]: InvalidPart: All non-trailing parts must have the same length

### ISSUE THREAD

**Issue by pablo-salad** [project-zot/zot#2142]
### zot version

ghcr.io/project-zot/zot-minimal-linux-amd64:v2.0.0

### Describe the bug

Pushing an image to Zot configured with remote store (Cloudflare R2) is reporting **InvalidPart: All non-trailing parts must have the same length** when is trying to complete a multipart upload.

### To reproduce

We prepared a Docker compose to reproduce this error. Just clone this [repository](https://github.com/pablo-salad/zot-r2-bug-report).
You'll find a Zot image with the remote configuration and an Ubuntu image with Skopeo installed to push the image.

**Configuration**
To setup the images, you'll need to have a [Cloudflare](https://www.cloudflare.com/) account, [create an R2 bucket](https://developers.cloudflare.com/r2/buckets/create-buckets/) and [create a R2 API Token](https://developers.cloudflare.com/r2/api/s3/tokens/) to access the bucket.
After this, open compose.yaml and fill these fields:
    - R2_ID (it's an alphanumeric in this R2 Dashboard Url https[]()://dash.cloudflare.com/**HERE**/r2</span>)
    - R2_BUCKET
    - R2_ACCESS_KEY
    - R2_SECRET_KEY

To run the test, execute `docker compose up` in the folder where the repository was cloned.

**Error**
After a few minutes, usually uploading a large layer, you will see **InvalidPart: All non-trailing parts must have the same length** error in the console.

### Expected behavior

Able to push any image without errors using Zot with remote storage.

### Screenshots

![image](https://github.com/project-zot/zot/assets/119421309/df2c8f94-4069-496f-88a9-596628580d00)

### Additional context

The current Zot configuration uses remote storage, in our case, [Cloudflare R2](https://developers.cloudflare.com/r2/) which has [S3 API compatibility](https://developers.cloudflare.com/r2/api/s3/api/).
The size of the images uploaded to the registry have an average of 5GB.
We had some luck pushing small images, less than 100MB, changing chunk size in the config but no success with larger ones.

**Comment by peusebiu** [comment]
Hello @pablo-salad 

Thank you for trying zot and for the feedback.

This seems to be a known issue in the library we are using for s3. We are waiting for a fix on their side.

Here is the issue: https://github.com/distribution/distribution/issues/3873
Here is the PR which is fixing it: https://github.com/distribution/distribution/pull/3940

**Comment by rchincha** [comment]
https://github.com/opencontainers/distribution-spec/issues/485

^ also this.

**Comment by kaulsh** [comment]
> Hello [@pablo-salad](https://github.com/pablo-salad)
> 
> Thank you for trying zot and for the feedback.
> 
> This seems to be a known issue in the library we are using for s3. We are waiting for a fix on their side.
> 
> Here is the issue: [distribution/distribution#3873](https://github.com/distribution/distribution/issues/3873) Here is the PR which is fixing it: [distribution/distribution#3940](https://github.com/distribution/distribution/pull/3940)

Looks like problems with multipart uploads were resolved. Can we get confirmation if R2 will now work as expected with Zot?

**Comment by andaaron** [comment]
Theoretically yes, it was release noted in https://github.com/distribution/distribution/releases/tag/v3.0.0-rc.1 and we use a later version.

We haven't tested though.

**Comment by kaulsh** [comment]
> Theoretically yes, it was release noted in https://github.com/distribution/distribution/releases/tag/v3.0.0-rc.1 and we use a later version.
> 
> We haven't tested though.

Thanks for the quick response. Will do some tests on my end and revert back.

**Comment by Sharpie** [comment]
I just tried connecting Zot v2.1.10 to Cloudflare R2 and pushing manifests results in a directory structure being created, but a bunch of incomplete multipart uploads.

So, it seems there is still an issue with using R2 on the latest release.

**Comment by Sharpie** [comment]
A follow-up: my issue wasn't with the zot registry. Upload times to R2 are much, much, much longer than saving locally to disk and there was a 10 second timeout around the process sending blob data to zot that was elapsing and canceling the operation.

This left abandoned multipart uploads behind on the R2 side.

**Comment by andaaron** [comment]
> A follow-up: my issue wasn't with the zot registry. Upload times to R2 are much, much, much longer than saving locally to disk and there was a 10 second timeout around the process sending blob data to zot that was elapsing and canceling the operation.
> 
> This left abandoned multipart uploads behind on the R2 side.

Hi @Sharpie, if you are still having this issue with the timeout and abandoned multipart uploads, please open a separate issue, and we'll track it there. Let's close this, as the original issue looks to be resolved.
